2015-04-20 22:42:29,194 [Thread-7:3288] [django.request:145] [base:get_response] [WARNING]- Not Found: /favicon.ico
2015-04-20 22:42:29,302 [Thread-8:5748] [django.request:145] [base:get_response] [WARNING]- Not Found: /
2015-04-20 22:42:29,359 [Thread-8:5748] [django.request:226] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "C:\Python27\lib\site-packages\django\contrib\sessions\middleware.py", line 38, in process_response
    request.session.save()
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\db.py", line 56, in save
    session_key=self._get_or_create_session_key(),
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 153, in _get_or_create_session_key
    self._session_key = self._get_new_session_key()
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 147, in _get_new_session_key
    if not self.exists(session_key):
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in exists
    return Session.objects.filter(session_key=session_key).exists()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 512, in exists
    return self.query.has_results(using=self.db)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 409, in has_results
    return bool(compiler.execute_sql(SINGLE))
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 450, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: django_session
